


‎      - name: Create Ethereum Identity
‎        run: node scripts/createNewEthereumIdentity.js

‎      - name: Link Human to Agent
‎        run: |
‎          node scripts/manualLinkHumanToAgent.js --challenge '{"name":"heyrival1","description":"heyrival1 AI Agent"}' 
